name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change to your default branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Update as needed

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Ensure this secret is correctly set

      - name: Deploy to Firebase Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: QuestionAnswerApp  # Replace with your Cloud Function name
          runtime: nodejs18
          project_id: "${{ secrets.GCP_PROJECT_ID }}"  # Ensure this secret is correctly set
          region: us-central1  # Change if using a different region
